### ISSUE TITLE
Combine other select quote functions into one keybindable function.

### ISSUE THREAD

**Issue by j-a-s-o-n-g** [MohammadMD1383/Actionable#3]
Is it possible to combine all of this into the one keybind "Select enclosing typing pairs"?

So the rules would be:
- If the PSI "elementType" equals "PLAIN_TEXT" or "SCRIPTING" it would execute the plain text search. If it is NOT this, then run the "Select literal element" as normal.
- For the plain text search, it would determine the quote to select between by the nearest ", ', or ` *outside* of the current selection (or closest symbol if nothing is selected)

This would get rid of the 3 extra key binds. Or we can keep the new keybinds in there for people who need separate keybinds. However personally I'd rather just have one keybind that does all of this based on the conditions listed above.

**Comment by MohammadMD1383** [comment]
re-implemented the action `Select Literal Element Under Caret`.
so now:
* it is language aware
* will fallback to 
    > select between by the nearest ", ', or `


currently supported languages can be found here:
https://github.com/MohammadMD1383/Actionable/blob/7276fc957350fab6a0a936527438b478c3c0d1cf/src/main/java/ir/mmd/intellijDev/Actionable/selection/Actions.kt#L65-L81

these changes are included in 7276fc957350fab6a0a936527438b478c3c0d1cf


---

this release doesn't address all the functionality requested here, so this issue will remain open

**Comment by MohammadMD1383** [comment]
> Can we tweak "Select Enclosing Typing Pairs" to also have this fallback but doesn't also include the quote symbols in the selection?

Yes, just again execute the action.

> Also noticed some inconsistent behavior with this ...

solved in the above commit

---

please consider closing this issue if there are no further problems. Thanks.

**Comment by j-a-s-o-n-g** [comment]
For some reason it's still not wokring for me.

1.) Create new scratch file > "plain text"
2.) Paste in `test "test test" test`
3.) Move Caret to: `test "test |test" test`
4.) `Select Enclosing Typing Pairs`
5.) Expected selection:

![image](https://user-images.githubusercontent.com/42372270/176887854-d26fcc3c-b444-453c-a1f5-b266374b49f3.png)

**Comment by j-a-s-o-n-g** [comment]
For some reason it's still not working for me. (v 3.10.0)

1.) Create new scratch file > "plain text"
2.) Paste in test "test test" test
3.) Move Caret to: test "test |test" test (or like below)

![image](https://user-images.githubusercontent.com/42372270/176892369-6921fc0a-2a99-4d0e-8ca1-b3dc07e9bfa2.png)

4.) Select Literal Element

![image](https://user-images.githubusercontent.com/42372270/176892470-34202158-696f-400f-8e90-197656483d7d.png)

5.) Expected selection:

![image](https://user-images.githubusercontent.com/42372270/176892538-f995ee53-07ec-4201-af76-4f4c369a59b9.png)

Edit: Let me update to 3.10.1 and see if it fixes it. I'll update when it becomes available.

**Comment by j-a-s-o-n-g** [comment]
Actually would it be possible to move the carets to the ends of each selection (like #5 in previous comment) once it selects it? That way it keeps the selection carets tidy.

**Comment by j-a-s-o-n-g** [comment]
Okay, the issue has been resolved in 3.10.1.

> > Can we tweak "Select Enclosing Typing Pairs" to also have this fallback but doesn't also include the quote symbols in the selection?
> 
> Yes, just again execute the action.

Would it make sense to make it so that it selects between quotes is the first execution, then second execution would also select the quote symbols? So flip this functionality?

**Comment by MohammadMD1383** [comment]
> Actually would it be possible to move the carets to the ends of each selection (like bullet 5 in previous comment) once it selects it? That way it keeps the selection carets tidy.

https://github.com/MohammadMD1383/Actionable/blob/93898646e2515a06655751eece9e0684c33bbca8/src/main/java/ir/mmd/intellijDev/Actionable/selection/SelectTextUnderCaretAction.kt#L9-L17

`Select Literal Element Under Caret` is one of the inheritors of this class, and changing caret position is not the purpose of this kind of functionality.

---

> Would it make sense to make it so that it selects between quotes is the first execution, then second execution would also select the quote symbols? So flip this functionality?

yes, this seems to be the correct way I should implement it; I will include it in future releases and will mention this issue in the commit message.
